name: weather
description: "Simple Weather App"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  lottie: ^3.3.1
  provider: ^6.1.5
  easy_localization: ^3.0.7+1
  geocoding: ^3.0.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - l10n/
    - assets/lottie/
    - assets/svg/
